apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghx-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.ghxServer.pvcStorage }}
  storageClassName: {{ .Values.ghxServer.storageClassName }}
